import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Hackathon Appwrite",
  description: "Generated by Elsa Chimba",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
      >
        {children}
      </body>
    </html>
  );
}
